### ISSUE TITLE
Empty copyright placeholder

### ISSUE THREAD

**Issue by alexanderkjall** [rust-secure-code/cargo-auditable#102]
The copyright info here is empty: https://github.com/rust-secure-code/cargo-auditable/blob/master/LICENSE-APACHE#L189

**Comment by Shnatsel** [comment]
That's part of the original license text. Note how it is situated under `APPENDIX: How to apply the Apache License to your work.`

AFAIK this is intentional.

**Comment by alexanderkjall** [comment]
Oh, I believe you are right, I have misunderstood this for a very long time. Thanks.
