### ISSUE TITLE
Add more fields to categories

### ISSUE THREAD

**Issue by insanitybit** [rust-secure-code/cargo-auditable#107]
I couldn't remember the name of this project and I tried searching "sbom" as a guess. I ended up finding it by looking up cargo-audit and (correctly) assuming it would be linked.

I see the categories are:
categories = ["development-tools::cargo-plugins", "encoding"]

Maybe it would be good to add some more? "security", "supply-chain", "sbom" or something? I don't know much about keywords.

**Comment by Shnatsel** [comment]
Thanks for the suggestion!

The categories are predefined, but we can use the [`keywords`](https://doc.rust-lang.org/cargo/reference/manifest.html#the-keywords-field) field for that.
