### ISSUE TITLE
No way to pass `-C link-arg=` when using both naked LLD and LLD via a compiler wrapper

### ISSUE THREAD

**Issue by astro** [rust-secure-code/cargo-auditable#121]
Problematic project: https://github.com/cloud-hypervisor/rust-hypervisor-firmware

As requested in https://github.com/NixOS/nixpkgs/pull/228106#discussion_r1181321478

**Comment by Shnatsel** [comment]
This is an issue with the https://github.com/cloud-hypervisor/rust-hypervisor-firmware breaking the `-C link-arg=` rustc flag. There's nothing that can be done on the `cargo auditable` side to solve this.

**Comment by Shnatsel** [comment]
I found a way to support naked linkers such as LLD, the fix has shipped in v0.6.7
