### ISSUE TITLE
Is this usable in conjunction with cargo-zigbuild / cargo-xwin?

### ISSUE THREAD

**Issue by fasterthanlime** [rust-secure-code/cargo-auditable#167]
See:

  * <https://github.com/rust-cross/cargo-zigbuild>
  * <https://github.com/rust-cross/cargo-xwin>

Those are both already wrapper around cargo — I haven't looked into the implementation details of either (or `cargo auditable` itself), but before I did, I just thought I would check if you've experimented with that before / have any thoughts on the matter.

**Comment by Shnatsel** [comment]
I have invested a lot of time into getting `sccache` working, but I haven't tried combining it with other Cargo subcommands.

`cargo auditable zigbuild` should probably work, and if not, it shouldn't be hard to get working. `cargo auditable` doesn't do anything particularly complicated in the `cargo` layer, it [simply sets a few environment variables and then calls cargo](https://github.com/rust-secure-code/cargo-auditable/blob/master/cargo-auditable/src/cargo_auditable.rs).

`cargo auditable` relies on passing a flag to the linker, which may be different under these particular subcommands. But as long as the CLI interface of the linker is the same as it usually is for the target triple, everything should work fine.

So please try it and let me know how it goes, I'm curious too!

**Comment by Shnatsel** [comment]
I've opened  #177 to fix an incompatibility with `cargo c`, but I've also confirmed that Cargo subcommands in general should work with `cargo auditable zigbuild` and such. Feel free to open an issue if some don't.
