### ISSUE TITLE
Support for 2024 edition

### ISSUE THREAD

**Issue by kpcyrd** [rust-secure-code/cargo-auditable#170]
I'm trying to switch to Rust 2024 Edition early to work around this problem:

https://brooksblog.bearblog.dev/rusts-sneaky-deadlock-with-if-let-blocks/

Right now cargo-auditable does not support this yet:

```
thread 'main' panicked at cargo-auditable/src/collect_audit_data.rs:87:36:
failed to parse cargo metadata output: Json(Error("unknown variant `2024`, expected one of `2015`, `2018`, `2021`", line: 1, column: 367319))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Let me know if there's anything I can do.

Thanks! :)

**Comment by Shnatsel** [comment]
Thank you for the report!

It seems this is an issue with `cargo_metadata` crate. We're currently using an old version of it. I see that the latest upstream version has a `#[non_exhaustive]` enum for the edition, so hopefully simply upgrading that crate will solve the problem.

**Comment by kpcyrd** [comment]
Thanks for the fast response, upgrading the `cargo_metadata` crate does indeed fix this, I've opened a pull request for this change. :)
