### ISSUE TITLE
`cargo auditable`: use `anyhow` crate for error handling

### ISSUE THREAD

**Issue by Shnatsel** [rust-secure-code/cargo-auditable#30]
Right now `cargo auditable` just has `.unwrap()` all over the place. That's fine for a prototype, but we'll need proper error handling to show nice error messages.

We should use `anyhow` crate for error handling, because that's what Cargo already uses, and it will make upstreaming simpler.

**Comment by VardhanThigle** [comment]
@Shnatsel 
I can work on this in the coming week.

**Comment by Shnatsel** [comment]
Now that I've looked through the codebase, it seems that errors are mostly caused by bugs in the program or something being very wrong with the environment. It should be fine to panic on those.
