### ISSUE TITLE
Registry URL omitted from dependency information

### ISSUE THREAD

**Issue by tofay** [rust-secure-code/cargo-auditable#35]
This means you can't identify if crates are from crates-io or an alternative registry, which may result in false positives in subsequent scanning.

Perhaps crates-io could be special cased, so that the URL is included? That would at least allow differentiation between crates-io and alternative registries. (I'm assuming `rust-audit` doesn't include the source from cargo_metadata directly for privacy reasons e.g leaking URLs/ git repo structure)

**Comment by Shnatsel** [comment]
> I'm assuming `rust-audit` doesn't include the source from cargo_metadata directly for privacy reasons e.g leaking URLs/ git repo structure

Yes, that's exactly the case.

There is a lot of ambiguity on whether a crate came from crates.io originally or not, even if we do provide that info. Vendored crates, as well crates.io crates mirrored into local registries will result either in false positives or false negatives no matter what, provided the names clash. If a crate came from a local registry but was originally mirrored from crates.io, not reporting a security issue with it would be a false negative. So even if we expose the "it came from crates.io" flag, I don't think auditing software should ignore vulnerabilities if the registry isn't crates.io.

Sadly I don't see a good solution here, other than avoiding name clashes.

**Comment by bjorn3** [comment]
Vendored crates using `[sources.crates-io] replace-with` must have the same source as the original on crates.io. Cargo enforces this using hashes in `Cargo.lock` and a file containing file hashes in the vendored source. So for all intents and purposes you can use the crates.io registry url for such vendored crates.

**Comment by Shnatsel** [comment]
Ah, that's encouraging. Can the same be applied to mirroring to private registries?

**Comment by Shnatsel** [comment]
Anyway, that's probably good enough to include crates.io as a separate source. The issue with registries, if it still exists, is not a showstopper - the tooling consuming this data can be tuned to produce either false positives or false negatives depending on the preferences of the user. It's probably not correct to force false positives on the format level.

**Comment by bjorn3** [comment]
> Can the same be applied to mirroring to private registries?

If replaced-with is used to replace the crates.io registry with the private registry, yes. If instead it is used as separate registry independent of crates.io, no. One thing to note though is thatvof the private registry is exclusively used, and crates.io is never used, Cargo.lock may still end up with incorrect hashes without any way for cargo to detect this. You could embed the hashes in the audit data to mitigate this.

**Comment by Shnatsel** [comment]
I've implemented recording crates.io as a distinct source in b7609b9daf1456ab48857ce3b7b2a12d0fd5d551; let me know if this solves it for your use case, or if anything else is needed.
