### ISSUE TITLE
Doesn't work on Mac

### ISSUE THREAD

**Issue by Shnatsel** [rust-secure-code/cargo-auditable#45]
Building on Mac without passing linker flags doesn't preserve the audit data. The Mac `ld` doesn't support the `--undefined` flag.

There is a documented flag `-u` that _seems_ to do what we need it to, but trying to actually use it results in the following error:

`ld: unknown option: -u AUDITABLE_VERSION_INFO`

The `-u` flag is documented in the [manpage](https://www.manpagez.com/man/1/ld/osx-10.3.php), so it's weird to see the linker reject it.

Both `-u AUDITABLE_VERSION_INFO` (with the space) and `-uAUDITABLE_VERSION_INFO` (without the space) fail.

**Comment by Shnatsel** [comment]
> Building on Mac without passing linker flags doesn't preserve the audit data

Or rather, it failed to round-trip. It's possible that the binary is built successfully, but out extraction tooling is looking in the wrong place. Unfortunately I don't have a mac to verify.

**Comment by Shnatsel** [comment]
Code in question:

https://github.com/Shnatsel/rust-audit/blob/2d1d13ae07ec3cbb229ed94159f520fa80038c04/cargo-auditable/src/rustc_wrapper.rs#L44-L46

**Comment by Shnatsel** [comment]
Okay, that should be `-Clink-arg=-Wl,-u,AUDITABLE_VERSION_INFO` with a comma instead of space or no space. That's progress.

**Comment by Shnatsel** [comment]
Well, `-Clink-arg=-Wl,-u,_AUDITABLE_VERSION_INFO` compiles, but audit data extraction still fails.

**Comment by tofay** [comment]
Fixed by https://github.com/rust-secure-code/cargo-auditable/pull/46
