### ISSUE TITLE
Provide a single function that extracts audit data from an executable

### ISSUE THREAD

**Issue by Shnatsel** [rust-secure-code/cargo-auditable#50]
Right now we have the full extraction pipeline in examples, which is not super complicated but is nevertheless manual.

`rust-audit-info` shows how it's all tied together; we should just put that into a function and make that a crate.

**Comment by pinkforest** [comment]
Happy to work on this as I need it

**Comment by Shnatsel** [comment]
So the example on the frontpage of https://docs.rs/auditable-extract/ is straightforward enough and is customizable enough that I just ended up copy-pasting it all over the place with some tweaks. But perhaps it can be made more user-friendly.

I think the function should accept a slice, and leave reading the file (or memory-mapping it, or whatever) to the caller. Enforcing a decompression limit would be nice, but optional - I guess you could provide that as an argument, `Option<usize>`. A unified error would be handy, I guess. That's about it?

The function should go into the `auditable-serde` crate, since `auditable-extract` is intentionally very minimal, and should be feature-gated (albeit enabled by default).

I think that's it?

**Comment by Shnatsel** [comment]
Or maybe just make `rust-audit-info` into a library and binary crate at the same time, and expose its functions that already have all sorts of limits implemented. That sounds like a good idea.

**Comment by pinkforest** [comment]
Yeah maybe we can do public higher level API that hides this stuff via implementation detail that has feature flags that what gets included. Just need the name for that higher level wrapper crate

The higher level API crate would also have some pub API semver guarantees

**Comment by pinkforest** [comment]
maybe `auditable-info` as crate name ?

**Comment by Shnatsel** [comment]
Yeah that works, and is available on crates.io :+1:
