### ISSUE TITLE
Signed binaries

### ISSUE THREAD

**Issue by pinkforest** [rust-secure-code/cargo-auditable#67]
Would it be feasible to extend cargo-auditable to signed binaries ? 

I would love to sign all the information and then use auditable also to check that the auditable information was signed correctly.

https://rust-lang.zulipchat.com/#narrow/stream/146229-wg-secure-code/topic/Signed.20binaries/near/293060631

**Comment by bjorn3** [comment]
You can sign a binary after running `cargo auditable` the same way you sign a regular binary for the respective OS, right?

**Comment by pinkforest** [comment]
Correct you could post-auditable.

I was additionally thinking that auditable could provide a mechanism to inject a signatures of the dependencies.

Nonetheless I would be keen to have builder to have it's own signing information in auditable format as well.

**Comment by bjorn3** [comment]
Dependencies don't have signatures, right?

**Comment by pinkforest** [comment]
Not currently but those still get linked. Especially in repeatable builds one would expect to get the same dependency.

**Comment by bjorn3** [comment]
You mean including a hash of all compiled rlibs that are linked into the executable?

**Comment by pinkforest** [comment]
Yep.

**Comment by Shnatsel** [comment]
Binaries compiled with `cargo auditable` certainly benefit from whole-binary signing, since it also makes the audit info impossible to tamper with after the binary is compiled.

I'm not sure how this proposal is different from regular binary signing, and why should it be handled by `cargo auditable` instead of a separate tool. Could you elaborate?

**Comment by pinkforest** [comment]
in zulip also Q came up:

> what's the use case? if the intent is to publish the binary, it might be interesting to use something like Sigstore


My A:
yeah publish.

I would prefer it in the binary instead of separate signature text file that ~never gets checked due to convenience factor cargo-auditable and tooling could provide it.

The tooling would just provide convenience to both insert and check the opinionated checksums without separate sign & check - 

I could just tell the users just to use to verify it came signed auditable with our sig with audit - also @tarcieri Sigstore sounds nice - does it support multisig flow or smth ?

**Comment by Shnatsel** [comment]
Embedding the signature into the binary in a way that leaves the binary easy to check is not easy. You are literally modifying the data you wanted to sign _after you signed it._ The procedure to revert the injection of the signature data is both security-critical and non-trivial.

I agree that it would synergize nicely with `cargo auditable`, but that project is sufficiently non-trivial to deserve its own tool. I'm going to close this as out of scope for `cargo auditable`, but you're welcome to get a repo for `cargo sig` going.

**Comment by pinkforest** [comment]
I also proposed that the dependencies in reproducible builds could be signed separately not just the whole binary.
