### ISSUE TITLE
Include rustc / toolchain version(s) ?

### ISSUE THREAD

**Issue by pinkforest** [rust-secure-code/cargo-auditable#70]
Related to: https://github.com/rustsec/advisory-db/discussions/1195, https://github.com/rustsec/rustsec/issues/673 and https://github.com/rustsec/advisory-db/issues/1404

It would be perhaps helpful to have the compiler / toolchain fingerprint / information included what it was used to build with ?

Also the buildflags e.g. compiler flags or "target linker" if we can fish it via CLI args / config | manifest might be much harder

I hope I didn't just miss this but didn't see it so :woman_shrugging:

**Comment by Shnatsel** [comment]
rustc already embeds it. This is also covered in the FAQ section in the readme.

There is no high-level wrapper for reading it, however. So perhaps it could be included in `auditable-extract` crate. Feel free to open an issue if you feel that would be useful.

**Comment by pinkforest** [comment]
I think I could work on that as part of https://github.com/rust-secure-code/cargo-auditable/issues/50

**Comment by Shnatsel** [comment]
These things should be decoupled because the rustc version is supposed to be always embedded while the audit info is only embedded when the binary was built with `cargo auditable`

**Comment by pinkforest** [comment]
yeah that makes sense
