### ISSUE TITLE
Failed to build with `sccache` wrapper

### ISSUE THREAD

**Issue by orhun** [rust-secure-code/cargo-auditable#80]
Hello, I'm using [sccache](https://github.com/mozilla/sccache) as rustc-wrapper:

```ini
# contents of .cargo/config

[build]
rustc-wrapper = "sccache"
```

This causes an error while using `cargo-auditable`:

```
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `sccache /usr/bin/cargo-auditable rustc - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit status: 2)
  --- stderr
  sccache: error: failed to execute compile
  sccache: caused by: Compiler not supported: "Unrecognized command: \"-E\"\n"
```

When I disable `sccache`, everything works as expected. Is there a way to work around this?

### Additional Info

Rust version: `rustc 1.66.0-nightly (6e95b6da8 2022-10-22)`
cargo-auditable version: `0.5.2`

**Comment by amousset** [comment]
This is known (cf. #55) and has been fixed in `sccache` (https://github.com/mozilla/sccache/pull/1280) but the fix was not released yet. The current workaround is to use build `sccache` from its `main` branch.

**Comment by orhun** [comment]
Thanks!
