### ISSUE TITLE
Cargo.lock is outdated

### ISSUE THREAD

**Issue by figsoda** [rust-secure-code/cargo-auditable#85]

**Comment by Shnatsel** [comment]
Oh, yeah, it is. It's a one-line change, I've pushed the new one.

Is there anything else you need me to do or can I close this?

**Comment by Shnatsel** [comment]
Oh. I forgot to push the tag. Done, thanks!

**Comment by figsoda** [comment]
the tag is pinned to the outdated Cargo.lock, could you maybe publish a new version?

**Comment by Shnatsel** [comment]
I've repointed the tag to the up-to-date Cargo.lock

**Comment by bjorn3** [comment]
Git doesn't pull changes to tags if you already pulled the old version.

**Comment by figsoda** [comment]
one thing i can think of is tag something like `v0.5.4-cargo-lock` or just not recovering at all

**Comment by Shnatsel** [comment]
Is this actually an issue for some build process somewhere? I'm not sure what the impact of the not-bumped Cargo.lock is, exactly.

**Comment by figsoda** [comment]
nixpkgs builds it with `--frozen`, the impact is just that we need to patch it Cargo.lock to make it up to date

**Comment by Shnatsel** [comment]
Alright, so I've moved the 0.5.4 tag to the commit containing the updated Cargo.lock file. If that's problematic for some reason, 0.5.3 can be used (the only changes are in the README.md) or a git snapshot can be packaged.

I'm going to leave it at that for this release, but I've opened #86 to prevent such issues happening in the future.
