### ISSUE TITLE
Run CI with `--frozen`

### ISSUE THREAD

**Issue by Shnatsel** [rust-secure-code/cargo-auditable#86]
Some distributions run their builds with `--frozen`. If the Cargo.lock committed into the tree is not up to date, this build will fail.

Now that `cargo auditable` is packaged by an increasing number of distributions, it's important to keep the package maintainer effort low. We should verify on CI that the package is buildable with `--frozen` to keep the checked-in Cargo.lock up to date.

See #85 for more details on the issue.

**Comment by figsoda** [comment]
running with `--locked` is probably good enough for this purpose
